tasks:
  - name: Script Task
    init: echo 'sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0'
    command: echo 'start script'

ports:
  - name: WeatherApp
    description: Swagger
    port: 5000
    onOpen: open-preview
    visibility: public
