tasks:
  - name: Install dotnet core
    init: sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
    command: cd WeatherApi ; dotnet build

ports:
  - name: WeatherApp
    description: Swagger
    port: 5000
    onOpen: open-preview
    visibility: public
